name: VindicterraStaffUtils
Author: Frostwolf74
version: '1.0-SNAPSHOT'
main: me.frostwolf74.vindicterraStaffUtils.VindicterraStaffUtils
api-version: '1.20'

commands:
  # utils
  staff:
    description: Toggles staff mode
    permission: VSU.staff
    aliases:
      - sm

  staffchat:
    description: Toggles staff chat mode or sends a message in staff chat
    permission: VSU.staffchat
    aliases:
      - sc

  freeze:
    description: Freeze player's movement, rotation and disable interactions
    permission: VSU.freeze

  inventorysee:
    description: View a player's inventory
    permission: VSU.inventorysee
    aliases:
      - invsee

  # punishments

  mute:
    description: Prevents a player from sending public chat messages
    permission: VSU.punish.mute

  kick:
    description: Kicks a player from the server
    permission: VSU.punish.kick

  ban:
    description: Bans a player from the server
    permission: VSU.punish.ban

permissions:
  VSU:
    children:
      VSU.staff:
        default: false
      VSU.staffchat:
        default: false
      VSU.freeze:
        default: false
      VSU.inventorysee:
        default: false
      VSU.rtp:
        default: false
      VSU.nightvision:
        default: false
      VSU.vanish:
        default: false
      VSU.onlineplayer:
        default: false
      VSU.punish.mute:
        default: false
      VSU.punish.kick:
        default: false
      VSU.punish.ban:
        default: false


